### ISSUE TITLE
The game closes after a few minutes of gameplay

### ISSUE THREAD

**Issue by RivelinoDomingo** [acreloaded/acr#253] opened 2021-01-08 01:23 UTC
Closes after a start time, using the latest release, v2.18.2 leaving this information in the terminal!
#####
#######
OpenAL Error (A003): invalid value, line 156
OpenAL Error (A003): invalid value, line 156
OpenAL Error (A003): invalid value, line 156
OpenAL Error (A003): invalid value, line 156
OpenAL Error (A003): invalid value, line 156
OpenAL Error (A003): invalid value, line 156
OpenAL Error (A003): invalid value, line 156
time remaining: 11 minutes
Selected next primary: Intervention
Selected next perk 1: 5
Selected next perk 2: 6
time remaining: 10 minutes
time remaining: 9 minutes
unnamed (0) is deploying a nuke! Stay alive!
stacktrace:
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0x14ee2f) [0x562af5d5de2f]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7ff484b56210]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0xe92c0) [0x562af5cf82c0]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0xea9cc) [0x562af5cf99cc]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0xee0da) [0x562af5cfd0da]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0xdbff7) [0x562af5ceaff7]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0xdc2ec) [0x562af5ceb2ec]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0x13d131) [0x562af5d4c131]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0xcb472) [0x562af5cda472]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(main+0x982) [0x562af5c22602]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff484b370b3]
/home/rivelino/Games/AssaultCube/bin_unix/linux_64_client(+0x18dba) [0x562af5c27dba]
ACR error (11) ()
OpenAL Error (A004): invalid operation, line 367
OpenAL Error (A004): invalid operation, line 367
OpenAL Error (A004): invalid operation, line 367
OpenAL Error (A004): invalid operation, line 367
OpenAL Error (A004): invalid operation, line 367
AL lib: (EE) alc_cleanup: 1 device not closed
###########
##############

I'm using Kde Neon; Kernel: 5.4.0-59-generic

**Comment by theonlypwner** [comment] 2021-01-12 03:10
duplicate of #215?

**Comment by theonlypwner** [comment] 2021-01-14 02:55
I'm closing this as a duplicate. Please try to get the corresponding line numbers in the stacktrace (see https://github.com/acreloaded/acr/issues/215#issuecomment-759891092) and post it there,

**Closed by theonlypwner** 2021-01-14 02:55 UTC
Labels: bug, duplicate

**Comment by theonlypwner** [comment] 2022-06-24 00:25
Duplicate of #215
