### ISSUE TITLE
AC Server Compatibility

### ISSUE THREAD

**Issue by notanewbie** [acreloaded/acr#222] opened 2019-02-11 01:23 UTC
How come the AC servers aren't compatible with AssaultCube Reloaded?

**Comment by theonlypwner** [comment] 2019-02-11 19:37
[We previously voted against it](http://forum.acr.victorz.ca/thread-1256.html).

**Comment by theonlypwner** [comment] 2019-02-11 19:38
Duplicate of #59.

**Comment by theonlypwner** [comment] 2019-02-11 19:39
[We previously voted against it](http://forum.acr.victorz.ca/thread-1256.html).

Duplicate of #59.

**Closed by theonlypwner** 2019-02-11 19:38 UTC
Labels: duplicate

**Comment by theonlypwner** [comment] 2022-06-24 02:10
Duplicate of #59
