### ISSUE TITLE
Assaultcube crash

### ISSUE THREAD

**Issue by ghost** [acreloaded/acr#252] opened 2020-06-29 22:59 UTC
ACR error (11) (Couldn't open packages/maps/official/preview/acr_recreation.jpg)
OpenAL Error (A004): invalid operation, line 367

OS: Arch Linux x86_64
Kernel: 5.7.5-arch1-1

**Comment by theonlypwner** [comment] 2020-07-29 17:12
duplicate of #215?

**Comment by Pauloo27** [comment] 2020-12-09 01:12
I got the same error. I'm no Arch as well.

I tried to clone the repo and compile it myself, the error persist.

**Comment by theonlypwner** [comment] 2021-01-14 02:56
I'm closing this as a duplicate.

If you can reproduce the issue, please try to get a stacktrace with line numbers (https://github.com/acreloaded/acr/issues/215#issuecomment-759891092) and post it there.

**Closed by theonlypwner** 2021-01-14 02:56 UTC
Labels: bug, duplicate

**Comment by theonlypwner** [comment] 2022-06-24 00:25
duplicate of #215

**Comment by theonlypwner** [comment] 2022-06-24 00:25
Duplicate of #215
