### ISSUE TITLE
OpenAL Error (A003): invalid value, line 156

### ISSUE THREAD

**Issue by Mte90** [acreloaded/acr#250] opened 2020-03-14 19:09 UTC
I am getting this error inside the game and in the console on linux: `OpenAL Error (A003): invalid value, line 156`

**Comment by Mte90** [comment] 2020-03-15 13:52
Seems that compiling the game fixed the problem maybe since the release there was some changes with the various dependencies

**Comment by theonlypwner** [comment] 2020-03-15 19:01
This seems to be similar to #215.

**Comment by theonlypwner** [comment] 2021-01-14 02:56
I'm closing this as a duplicate.

If you can reproduce the issue, please try to get a stacktrace with line numbers (https://github.com/acreloaded/acr/issues/215#issuecomment-759891092) and post it there.

**Closed by theonlypwner** 2021-01-14 02:56 UTC
Labels: bug, duplicate

**Comment by theonlypwner** [comment] 2022-06-24 00:26
Duplicate of #215
